language: php

notifications:
  email:
    on_success: never

php:
  - 7.4
  - 8.0

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer validate --strict
  - composer install -n

script:
  - composer test -- --coverage-clover=coverage.xml
  - composer cs-fix
  - composer phpstan
  - composer psalm
  - composer phpqa

after_success:
- bash <(curl -s https://codecov.io/bash)
